language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1
  - 8.2

env:
  matrix:
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

#after_script:
  #- wget https://scrutinizer-ci.com/ocular.phar
  #- if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
